version: '3.7'
networks:
  dspacenet:
services:
  dspace:
    container_name: bycovid-harvester
    depends_on:
    - dspacedb
    image: "${DOCKER_OWNER:-dspace}/dspace:${DSPACE_VER:-dspace-6_x-jdk8-test}"
    build:
      context: .
      dockerfile: Dockerfile.jdk8-test
    networks:
      dspacenet:
    ports:
    - published: 8080
      target: 8080
    stdin_open: true
    tty: true
    volumes:
    - ./dspace/src/main/docker-compose/local.cfg:/dspace/config/local.cfg
    - ./dspace/src/main/docker-compose/xmlui.xconf:/dspace/config/xmlui.xconf
    - assetstore:/dspace/assetstore
    - solr_authority:/dspace/solr/authority/data
    - solr_oai:/dspace/solr/oai/data
    - solr_search:/dspace/solr/search/data
    - solr_statistics:/dspace/solr/statistics/data
    - xmlshare:/shared
  transformer:
    container_name: bycovid-transformer
    depends_on:
    - dspace
    build:
      context: .
      dockerfile: Dockerfile.py3
    networks:
      dspacenet:
    stdin_open: true
    tty: true
    volumes:
    - xmlshare:/shared
    command: /bin/bash
  dspacedb:
    container_name: bycovid-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /pgdata
    image: dspace/dspace-postgres-pgcrypto
    networks:
      dspacenet:
    stdin_open: true
    tty: true
    volumes:
    - pgdata:/pgdata
volumes:
  assetstore:
  pgdata:
  solr_authority:
  solr_oai:
  solr_search:
  solr_statistics:
  xmlshare:
